tool
extends Spatial


# Declare member variables here. Examples:
# var a = 2
# var b = "text"
onready var skel = $Character/Rig/Skeleton

# Called when the node enters the scene tree for the first time.
func _ready():
	var idx_upperarm_l = skel.find_bone("upperarm.l")
	var idx_lowerarm_l = skel.find_bone("lowerarm.l")
	skel.set_bone_pose(idx_upperarm_l,Transform.IDENTITY.rotated(Vector3.FORWARD,PI/4))
	skel.set_bone_pose(idx_lowerarm_l,Transform.IDENTITY.rotated(Vector3.FORWARD,PI/4))


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
